name: Build and Publish Linux App

on:
  push:
    branches:
      - pipeline
  pull_request:
    branches:
      - pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: electron-client
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install ImageMagick
      run: brew install imagemagick

    - name: Generate Iconset
      run: |
        npm i -g ts-node
        ts-node scripts/generate-icon.ts linux

    - name: Package Electron App
      run: |
        npm run publish -- --platform=linux --arch=x64

