name: Build and Create Signed DMG Installer

on:
  push:
    branches:
      - pipeline
  pull_request:
    branches:
      - pipeline

jobs:
  build:
    env:
        APP_NAME: FlashBanger
        IMAGE_PATH: packaging/app_icon.png
        BUNDLE_ID: com.mappso.flashbanger
        BACKGROUND_IMAGE: packaging/background.png
        ICON_OUTPUT_DIR: packaging/icon.iconset
    runs-on: macos-latest
    defaults:
      run:
        working-directory: electron-client
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install ImageMagick
      run: brew install imagemagick

    - name: Generate Iconset
      run: |
        npm i -g ts-node
        ts-node scripts/generate-icon.ts

    - name: Create ICNS file
      run: iconutil -c icns ${{ env.ICON_OUTPUT_DIR }}

    - name: Download Developer Certificate
      run: |
        echo "${{ secrets.APPLE_DEVELOPER_CERTIFICATE }}" | base64 --decode > certificate.p12

    - name: Import Certificate into Keychain
      run: |
        security create-keychain -p password build.keychain
        security import certificate.p12 -k build.keychain -P "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
        security list-keychains -d user -s build.keychain
        security unlock-keychain -p password build.keychain
        security set-keychain-settings
        security find-identity -v -p codesigning

    - name: Package Electron App
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      run: |
        npm run make -- --platform=darwin --arch=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.APP_NAME }}.dmg
        path: electron-client/out/make/*.dmg
